### ISSUE TITLE
Method not enabled

### ISSUE THREAD

**Issue by ppoliani** [blk-io/epirus-free#20]
I'm getting some errors in the log files.

```
2020-01-20 13:28:59.251 INFO 1 --- [ Thread-903] i.b.q.e.jobs.IngestHistoricalBlocksJob : Ingesting Historical Blocks from: 664..693 (30)
2020-01-20 13:28:59.314 INFO 1 --- [ Thread-903] i.b.q.e.ingestor.IngestionService : fetching 30 blocks took 0s
2020-01-20 13:28:59.317 INFO 1 --- [ Thread-903] i.b.q.e.ingestor.IngestionService : ingesting block range 664..693 (30)
2020-01-20 13:28:59.321 INFO 1 --- [ Thread-903] i.b.q.e.i.handlers.TransactionIngestor : Ingesting Transaction
2020-01-20 13:28:59.325 INFO 1 --- [ Thread-903] i.b.q.e.i.h.ContractCreationIngestor : Ingesting ContractCreation
2020-01-20 13:28:59.325 INFO 1 --- [ Thread-903] i.b.q.e.i.h.ContractTransactionIngestor : Ingesting ContractTransaction
2020-01-20 13:28:59.330 INFO 1 --- [ Thread-903] i.b.q.e.i.handlers.AccountIngestor : Ingesting Account
2020-01-20 13:28:59.332 INFO 1 --- [ Thread-903] i.b.q.e.i.h.ContractParamIngestor : Ingesting contract parameters from 0 accounts
2020-01-20 13:28:59.332 INFO 1 --- [ Thread-903] i.b.q.e.ingestor.handlers.EventIngestor : Ingesting Events
2020-01-20 13:28:59.369 INFO 1 --- [ Thread-903] i.b.q.e.i.h.TransactionParamIngestor : Ingesting Transaction Params
2020-01-20 13:28:59.371 INFO 1 --- [ Thread-903] i.b.q.e.ingestor.IngestionService : ingesting block range 664..693 (30) took 0s
2020-01-20 13:28:59.497 INFO 1 --- [ Thread-905] i.b.q.e.jobs.IngestHistoricalBlocksJob : Ingesting Historical Blocks from: 694..783 (90)
2020-01-20 13:28:59.767 ERROR 1 --- [ scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler : Unexpected error occurred in scheduled task.
java.util.concurrent.CompletionException: org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 400; {
"jsonrpc" : "2.0",
"id" : 21182,
"error" : {
"code" : -32604,
"message" : "Method not enabled"
}
}
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 400; {
"jsonrpc" : "2.0",
"id" : 21182,
"error" : {
"code" : -32604,
"message" : "Method not enabled"
}
}
at org.web3j.protocol.http.HttpService.performIO(HttpService.java:173)
at org.web3j.protocol.Service.send(Service.java:42)
at org.web3j.protocol.core.Request.send(Request.java:81)
at io.blk.quorum.explorer.ingestor.IngestionService.privateTransactionPayload(IngestionService.kt:103)
at io.blk.quorum.explorer.ingestor.IngestionService.getTransaction(IngestionService.kt:89)
at io.blk.quorum.explorer.ingestor.IngestionService.ingest(IngestionService.kt:64)
at io.blk.quorum.explorer.jobs.IngestHistoricalBlocksJob.ingestRange(IngestHistoricalBlocksJob.kt:76)
at io.blk.quorum.explorer.jobs.IngestHistoricalBlocksJob.run(IngestHistoricalBlocksJob.kt:32)
at io.blk.quorum.explorer.scheduler.ScheduledTasks$ingestionJob$historicalBlocksJob$1.run(ScheduledTasks.kt:27)
... 2 common frames omitted

```

I wonder which json-rpc method is it trying to execute.

**Comment by antonydenyer** [comment]
You need the admin endpoints enabled. This is so that we can tell what client you are running.

**Comment by ppoliani** [comment]
Hi @antonydenyer,

I'm running Hyperledger Besu version 1.3.8

**Comment by antonydenyer** [comment]
Are you running the quickstart? If so which one?

**Comment by ppoliani** [comment]
I'm deploying the services using k8s. I follow this instructions https://github.com/PegaSysEng/besu-kubernetes/tree/master/kubectl/private-network-clique

**Comment by antonydenyer** [comment]
You need to add ADMIN to the list of enabled rpc methods on node that you want to connect to.  https://besu.hyperledger.org/en/stable/HowTo/Interact/APIs/Using-JSON-RPC-API/#api-methods-enabled-by-default

**Comment by ppoliani** [comment]
@antonydenyer thanks for that mate. I will try that and let you know.
